### ISSUE TITLE
Analyse two part demos, where the game did not start and finish in one demo file

### ISSUE THREAD

**Issue by SteveSzabo** [akiver/cs-demo-manager#694]
### Describe the bug

 The problem here is that the demo file didn't start and end in one file, it was covered over two separate demo files. I suspect that the demo manager is not handling this due to expecting to see something like a "start" and "end match" event.

Downloaded the final game of the BB Dacha 2023 grand finals - VP vs Spirit (link below), and found that match 5 of the series was recorded in two parts (instead of one demo file covering start > end).

Part 2 demo file, starts on around 23.

Not sure if this is truly a bug, but more of a feature request for it to be handled better? so apologies in advance if this has been raised incorrectly!

### Demo links

https://www.hltv.org/matches/2368508/virtuspro-vs-spirit-betboom-dacha-2023
Game 5: Anubis

### Steps to reproduce

1. Start Application
2. Go to 'dem' on the left hand side navigation
3. Select the `virtuspro-vs-spirit-m5-anubis-p1` or `virtuspro-vs-spirit-m5-anubis-p2` demo
4. Click `analyze`

### Expected behavior

I would have hoped it would have still loaded something even though it didn't officially finish the game in the first part demo file.

I can watch the demo back without an issue using the demo manager `watch` button.

### How often does this bug happen?

None

### Part 1 demo Logs:
```
{unknown event "player_activate" 0}
{unknown event "player_activate" 0}
{unknown event "player_activate" 0}
Command failed: psql -c "\copy rounds(number,start_tick,start_frame,freeze_time_end_tick,freeze_time_end_frame,end_tick,end_frame,end_officially_tick,end_officially_frame,team_a_name,team_b_name,team_a_score,team_b_score,team_a_side,team_b_side,team_a_start_money,team_b_start_money,team_a_equipment_value,team_b_equipment_value,team_a_money_spent,team_b_money_spent,team_a_economy_type,team_b_economy_type,duration,end_reason,winner_name,winner_side,overtime_number,match_checksum) FROM 'C:\Users\Szabo\AppData\Local\Temp\cs-demo-manager\virtuspro-vs-spirit-m5-anubis-p1_rounds.csv' CSV DELIMITER ','" "postgresql://*****:*****@*****:****/csdm"
ERROR:  null value in column "winner_name" of relation "rounds" violates not-null constraint
DETAIL:  Failing row contains (66, 9ca05254d68442e1, 22, 225750, 237024, -1, -1, 0, 0, 0, 0, Spirit, Virtus.pro, 9, 13, 2, 3, 11100, 26550, 24050, 20850, 0, 0, full, full, -3541064, 0, null, 0, 0).
CONTEXT:  COPY rounds, line 22: "22,225750,237024,-1,-1,0,0,0,0,Spirit,Virtus.pro,9,13,2,3,11100,26550,24050,20850,0,0,full,full,-354..."

```
### Part 2 demo Logs.
```
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
{received GameEvent but event descriptors are missing 3}
missing game event descriptors (ErrMissingGameEventDescriptors)
stacktrace:
goroutine 6 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x5e
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.NewParserWithConfig.func1({0xa44380, 0xc0008b6fb0})
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/parser.go:388 +0x2a
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover.func1()
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:197 +0x3b
panic({0xa44380?, 0xc0008b6fb0?})
	runtime/panic.go:914 +0x21f
github.com/markus-wa/godispatch.callConsumerCode.func1()
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:122 +0x54
panic({0xa44380?, 0xc0008b6fa0?})
	runtime/panic.go:914 +0x21f
github.com/markus-wa/godispatch.callConsumerCode.func1()
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:122 +0x54
panic({0xa07360?, 0xc0008b6f90?})
	runtime/panic.go:914 +0x21f
github.com/akiver/cs-demo-analyzer/pkg/api.(*Analyzer).registerCommonHandlers.func12({{0xb10e8a, 0x34}, 0x3})
	github.com/akiver/cs-demo-analyzer/pkg/api/analyzer.go:727 +0xce
reflect.Value.call({0x9dd4a0?, 0xc000042f70?, 0x668748?}, {0xafe9be, 0x4}, {0xc000095560, 0x1, 0xc0002aac30?})
	reflect/value.go:596 +0xce7
reflect.Value.Call({0x9dd4a0?, 0xc000042f70?, 0x3?}, {0xc000095560?, 0xd300000000000000?, 0x4?})
	reflect/value.go:380 +0xb9
github.com/markus-wa/godispatch.callConsumerCode({0x9dd4a0?, 0xc000042f70?, 0x18?}, {0xc000095560?, 0xa3f400?, 0x0?})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:125 +0x3f
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc000044660, {0xa3f400, 0xc000bdf0b0})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:111 +0x1d4
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).handleGameEvent(0xc000063860, 0x1?)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/game_events.go:50 +0x116
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).handleGameEventS2(0x0?, 0xc000087320)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/game_events.go:97 +0x285
reflect.Value.call({0x9de520?, 0xc000042ea0?, 0xc0002ab710?}, {0xafe9be, 0x4}, {0xc000095ef8, 0x1, 0x3?})
	reflect/value.go:596 +0xce7
reflect.Value.Call({0x9de520?, 0xc000042ea0?, 0x0?}, {0xc000095ef8?, 0xf100000000000000?, 0x1?})
	reflect/value.go:380 +0xb9
github.com/markus-wa/godispatch.callConsumerCode({0x9de520?, 0xc000042ea0?, 0xab8fe0?}, {0xc000095ef8?, 0x6670a6?, 0x68d88e?})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:125 +0x3f
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc000044600, {0xaa2380, 0xc000087320})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:111 +0x1d4
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover(0xc000044618?, {0xaa2380?, 0xc000087320?})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:202 +0x4f
github.com/markus-wa/godispatch.(*Dispatcher).dispatchQueue(0xc000044600, 0x0?)
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:177 +0xd0
created by github.com/markus-wa/godispatch.(*Dispatcher).AddQueues in goroutine 1
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:162 +0x18a

```

### Environment information

Version: 3.0.2
OS: win32 x64 10.0.19045
Electron: 28.0.0
Chrome: 120.0.6099.56
Last database migrations:
v1 - 2023-12-11T10:39:15.145Z

**Comment by akiver** [comment]
Hi,

As mentioned in the [FAQ](https://cs-demo-manager.com/docs/faq/general#does-it-work-with-demos-split-in-multiple-files) this is not supported.
There is no plan to support it because it would require a lot of work for an edge case (demo identification, analysis, UI...).

> I would have hoped it would have still loaded something even though it didn't officially finish the game in the first part demo file.

It could work - it depends on when the demo stopped.
The linked demo failed because it stopped in the middle of a round, and a round without a winner should not be possible.
While allowing rounds without a winner is technically possible, data integrity is more important to prevent bugs.

Thank you for your understanding

**Comment by SteveSzabo** [comment]
Thanks Akiver, apologies for overlooking this in the FAQ!
