### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by bry678** [akiver/cs-demo-manager#709]
### Describe the bug

im trying to use faceit and i typed in my username but it crashed and now every time i select faceit it just crash

### Steps to reproduce

https://github.com/akiver/cs-demo-manager/assets/154054857/f714a638-e790-4f2c-819d-150e91a671a2

### Expected behavior

when i entered my username it shouldve loaded all my faceit demos 

### How often does this bug happen?

None

### Log file

[csdm.log](https://github.com/akiver/cs-demo-manager/files/13695664/csdm.log)

### Environment information

Version: 3.0.5
OS: win32 x64 10.0.22631
Electron: 28.0.0
Chrome: 120.0.6099.56

### Additional context

```
TypeError: Cannot read properties of undefined (reading 'score')
    at file:///C:/Users/688br.BRYANGAMINGPC/AppData/Local/Programs/cs-demo-manager/resources/app.asar/assets/index-FdmQ7VVf.js:303:153647
    at Array.map (<anonymous>)
    at Sidebar (file:///C:/Users/688br.BRYANGAMINGPC/AppData/Local/Programs/cs-demo-manager/resources/app.asar/assets/index-FdmQ7VVf.js:303:153400)
    at Xh (file:///C:/Users/688br.BRYANGAMINGPC/AppData/Local/Programs/cs-demo-manager/resources/app.asar/assets/index-FdmQ7VVf.js:38:21803)
    at Wk (file:///C:/Users/688br.BRYANGAMINGPC/AppData/Local/Programs/cs-demo-manager/resources/app.asar/assets/index-FdmQ7VVf.js:40:48739)
    at Vk (file:///C:/Users/688br.BRYANGAMINGPC/AppData/Local/Programs/cs-demo-manager/resources/app.asar/assets/index-FdmQ7VVf.js:40:43981)
    at Uk (file:///C:/Users/688br.BRYANGAMINGPC/AppData/Local/Programs/cs-demo-manager/resources/app.asar/assets/index-FdmQ7VVf.js:40:43902)
    at Jk (file:///C:/Users/688br.BRYANGAMINGPC/AppData/Local/Programs/cs-demo-manager/resources/app.asar/assets/index-FdmQ7VVf.js:40:43742)
    at Ok (file:///C:/Users/688br.BRYANGAMINGPC/AppData/Local/Programs/cs-demo-manager/resources/app.asar/assets/index-FdmQ7VVf.js:40:39714)
    at Fk (file:///C:/Users/688br.BRYANGAMINGPC/AppData/Local/Programs/cs-demo-manager/resources/app.asar/assets/index-FdmQ7VVf.js:40:40616)
```

**Comment by giou** [comment]
This exact issue still happening to me even after using the api key. v3.17.0

<details>
<summary>Error log</summary>

```
TypeError: Cannot read properties of undefined (reading 'score')
    at t12 (file:///C:/Users/g/AppData/Local/Programs/cs-demo-manager/resources/app.asar/assets/index-d8MfAkVm.js:350:522429)
    at Array.map (<anonymous>)
    at Sidebar$1 (file:///C:/Users/g/AppData/Local/Programs/cs-demo-manager/resources/app.asar/assets/index-d8MfAkVm.js:350:522729)
    at renderWithHooks (file:///C:/Users/g/AppData/Local/Programs/cs-demo-manager/resources/app.asar/assets/index-d8MfAkVm.js:8:94537)
    at updateFunctionComponent (file:///C:/Users/g/AppData/Local/Programs/cs-demo-manager/resources/app.asar/assets/index-d8MfAkVm.js:8:148494)
    at beginWork (file:///C:/Users/g/AppData/Local/Programs/cs-demo-manager/resources/app.asar/assets/index-d8MfAkVm.js:8:174199)
    at performUnitOfWork (file:///C:/Users/g/AppData/Local/Programs/cs-demo-manager/resources/app.asar/assets/index-d8MfAkVm.js:8:264043)
    at workLoopSync (file:///C:/Users/g/AppData/Local/Programs/cs-demo-manager/resources/app.asar/assets/index-d8MfAkVm.js:8:261100)
    at renderRootSync (file:///C:/Users/g/AppData/Local/Programs/cs-demo-manager/resources/app.asar/assets/index-d8MfAkVm.js:8:260579)
    at performWorkOnRoot (file:///C:/Users/g/AppData/Local/Programs/cs-demo-manager/resources/app.asar/assets/index-d8MfAkVm.js:8:250621)
```

</details>

**Comment by akiver** [comment]
What's the faceit username?

**Comment by giou** [comment]
@akiver 

> What's the faceit username?

giou

**Comment by akiver** [comment]
I couldn't reproduce the issue but pushed a potential fix that will be in the next version.

**Comment by giou** [comment]
Still happening in v3.17.1 but only with my username. Tested a fresh database and the problem is gone.

<details>
<summary>Old database info</summary>

```
Version: 3.17.1
OS: win32 x64 10.0.26200
Electron: 39.2.7
Chrome: 142.0.7444.235
Last database migrations:
v10 - 2025-12-25T22:04:25.520Z
v9 - 2025-10-18T11:22:35.857Z
v8 - 2025-07-31T19:49:16.700Z
v6 - 2025-01-07T23:34:55.632Z
```

</details>
