### ISSUE TITLE
Demo analyze error

### ISSUE THREAD

**Issue by bsolyom** [akiver/cs-demo-manager#723]
### Describe the bug

I downloaded a demo as usual but when i tried to analyze it I got that error. 

### Demo links

[http://replay191.valve.net/730/003658595928920555665_1323070981.dem.bz2](url)

### Steps to reproduce

I downloaded the demo file (bz2), extracted and renamed it to .dem as ususal but I got that error.

### Expected behavior

I would expected to analyze the demo

### How often does this bug happen?

Only once

### Log file

```
property 'm_unCurrentEquipmentValue' not found
stacktrace:
goroutine 19 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x5e
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.NewParserWithConfig.func1({0x9b53c0?, 0xc0007d4910})
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/parser.go:388 +0x2f
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover.func1()
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:197 +0x3b
panic({0x9b53c0?, 0xc0007d4910?})
	runtime/panic.go:914 +0x21f
github.com/markus-wa/godispatch.callConsumerCode.func1()
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:122 +0x54
panic({0x9b53c0?, 0xc0007d48f0?})
	runtime/panic.go:914 +0x21f
github.com/markus-wa/godispatch.callConsumerCode.func1()
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:122 +0x54
panic({0x94ba60?, 0xc0007d48d0?})
	runtime/panic.go:914 +0x21f
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/sendtables2.(*Entity).PropertyValueMust(0x5d98d3?, {0xa78fa4, 0x19})
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/sendtables2/entity.go:163 +0x134
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/common.getUInt64(...)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/common/entity_util.go:18
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/common.(*Player).EquipmentValueCurrent(0xc0007a4b60)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/common/player.go:432 +0x129
github.com/akiver/cs-demo-analyzer/pkg/api.newPlayerEconomy(0xc000090960, 0xc0007a4b60)
	github.com/akiver/cs-demo-analyzer/pkg/api/player_economy.go:32 +0x5c
github.com/akiver/cs-demo-analyzer/pkg/api.(*Analyzer).createPlayersEconomies(0xc000090960)
	github.com/akiver/cs-demo-analyzer/pkg/api/analyzer.go:538 +0x10a
github.com/akiver/cs-demo-analyzer/pkg/api.createValveAnalyzer.func5({0x0?, 0x0?})
	github.com/akiver/cs-demo-analyzer/pkg/api/valve.go:43 +0x1b
reflect.Value.call({0x94e660?, 0xc0000929c0?, 0x0?}, {0xa6fabe, 0x4}, {0xc000411600, 0x1, 0xc000411530?})
	reflect/value.go:596 +0xce7
reflect.Value.Call({0x94e660?, 0xc0000929c0?, 0x12c62d33270?}, {0xc000411600?, 0x150000c000eea000?, 0x2?})
	reflect/value.go:380 +0xb9
github.com/markus-wa/godispatch.callConsumerCode({0x94e660?, 0xc0000929c0?, 0x5?}, {0xc000411600?, 0xc001910540?, 0x1010000000000?})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:125 +0x3f
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc0001cc5a0, {0x9b0580, 0xc0016bfb10})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:111 +0x1d4
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.gameEventHandler.dispatch(...)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/game_events.go:114
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).processRoundProgressEvents(0xc000084b60)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/game_events.go:1077 +0x13d
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).processFrameGameEvents(0xc000084b60)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/game_events.go:1129 +0x56
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).handleFrameParsed(0xc000084b60, 0x0)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/parsing.go:524 +0x18
reflect.Value.call({0x94f420?, 0xc00008ae10?, 0xc0002777d0?}, {0xa6fabe, 0x4}, {0xc000411ef8, 0x1, 0x2?})
	reflect/value.go:596 +0xce7
reflect.Value.Call({0x94f420?, 0xc00008ae10?, 0x0?}, {0xc000411ef8?, 0x7100000000000000?, 0x0?})
	reflect/value.go:380 +0xb9
github.com/markus-wa/godispatch.callConsumerCode({0x94f420?, 0xc00008ae10?, 0xa21180?}, {0xc000411ef8?, 0x5d70a6?, 0x0?})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:125 +0x3f
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc0001cc540, {0x93a800, 0xf63600})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:111 +0x1d4
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover(0xc0001cc558?, {0x93a800?, 0xf63600?})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:202 +0x4f
github.com/markus-wa/godispatch.(*Dispatcher).dispatchQueue(0xc0001cc540, 0x0?)
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:177 +0xd0
created by github.com/markus-wa/godispatch.(*Dispatcher).AddQueues in goroutine 1
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:162 +0x18a
```

### Environment information

Version: 3.0.7
OS: win32 x64 10.0.19045
Electron: 28.0.0
Chrome: 120.0.6099.56

**Comment by akiver** [comment]
Will be fixed with https://github.com/markus-wa/demoinfocs-golang/pull/489
