### ISSUE TITLE
Memory issues

### ISSUE THREAD

**Issue by artemmiz1** [akiver/cs-demo-manager#757]
### Describe the bug

When trying to analyze the demos after the update from 2 days ago, I can't quite do it as it sometimes gives me an error and sometimes the app becomes fully black and uninteractable. Get the following error runtime: VirtualAlloc of 11654799360 bytes failed with errno=1455 fatal error: out of memory. Have 8 gigabytes on this laptop and with almost all other apps closed, the manager uses over 7 GB and unable to analyze the demo. Worked fine all the time

### Demo links

Every demo after the update

### Steps to reproduce

1. Start the application
2. Click analyze 
3. Get the error

### Expected behavior

I would expect seeing a successful demo analysis but I see this error message that uses all memory and causes my laptop to lag

### How often does this bug happen?

None

### Log file

runtime: VirtualAlloc of 11654799360 bytes failed with errno=1455
fatal error: out of memory

runtime stack:
runtime.throw({0x65469b?, 0xc590ab0000?})
	runtime/panic.go:1077 +0x65 fp=0x5be4bffbe8 sp=0x5be4bffbb8 pc=0x1dac65
runtime.sysUsedOS(0xc5063f0000, 0x2b6ae2000)
	runtime/mem_windows.go:83 +0x1bb fp=0x5be4bffc48 sp=0x5be4bffbe8 pc=0x1ba51b
runtime.sysUsed(...)
	runtime/mem.go:77
runtime.(*mheap).allocSpan(0xb098a0, 0x15b571, 0x0, 0x8a?)
	runtime/mheap.go:1351 +0x487 fp=0x5be4bffce8 sp=0x5be4bffc48 pc=0x1cbc87
runtime.(*mheap).alloc.func1()
	runtime/mheap.go:968 +0x5c fp=0x5be4bffd30 sp=0x5be4bffce8 pc=0x1cb43c
traceback: unexpected SPWRITE function runtime.systemstack
runtime.systemstack()
	runtime/asm_amd64.s:509 +0x49 fp=0x5be4bffd40 sp=0x5be4bffd30 pc=0x206609

goroutine 6 [running]:
runtime.systemstack_switch()
	runtime/asm_amd64.s:474 +0x8 fp=0xc000437180 sp=0xc000437170 pc=0x2065a8
runtime.(*mheap).alloc(0xc000061d40?, 0x330072e6ee6ac?, 0x0?)
	runtime/mheap.go:962 +0x5b fp=0xc0004371c8 sp=0xc000437180 pc=0x1cb39b
runtime.(*mcache).allocLarge(0xc000437228?, 0x2b6ae0b00, 0x0?)
	runtime/mcache.go:234 +0x85 fp=0xc000437210 sp=0xc0004371c8 pc=0x1b93e5
runtime.mallocgc(0x2b6ae0b00, 0x551b40, 0x1)
	runtime/malloc.go:1127 +0x4f6 fp=0xc000437278 sp=0xc000437210 pc=0x1b0596
runtime.makeslice(0xc000a0c400?, 0x214f00?, 0xb47948?)
	runtime/slice.go:103 +0x49 fp=0xc0004372a0 sp=0xc000437278 pc=0x1edac9
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/sendtables2.(*fieldState).set(0xc0007cf540?, 0xc000b0a960, {0x52cc20?, 0xaa0968})
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/sendtables2/field_state.go:38 +0x9f fp=0xc000437310 sp=0xc0004372a0 pc=0x46561f
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/sendtables2.(*Entity).readFields(0xc0005acd20, 0xc0002abce0?, 0xc000437608)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/sendtables2/entity.go:422 +0x12e fp=0xc000437450 sp=0xc000437310 pc=0x45fa0e
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/sendtables2.(*Parser).OnPacketEntities(0xc00007aaf0, 0xc0001b4750)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/sendtables2/entity.go:527 +0x618 fp=0xc000437720 sp=0xc000437450 pc=0x460178
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.sendTableParser.OnPacketEntities-fm(0x1?)
	<autogenerated>:1 +0x2b fp=0xc000437740 sp=0xc000437720 pc=0x49e1eb
runtime.call16(0xc00079ff50, 0xc000008840, 0x0, 0x0, 0x0, 0x8, 0xc000437c90)
	runtime/asm_amd64.s:747 +0x48 fp=0xc000437760 sp=0xc000437740 pc=0x206ae8
runtime.reflectcall(0x62ee40?, 0xc0001b4750?, 0x1?, 0x656f11?, 0x0?, 0x12?, 0x62ee40?)
	<autogenerated>:1 +0x36 fp=0xc0004377a0 sp=0xc000437760 pc=0x20d496
reflect.Value.call({0x5461a0?, 0xc000008840?, 0xc0002ab890?}, {0x65169c, 0x4}, {0xc000437ef8, 0x1, 0x1?})
	reflect/value.go:596 +0xce7 fp=0xc000437db0 sp=0xc0004377a0 pc=0x26aa67
reflect.Value.Call({0x5461a0?, 0xc000008840?, 0x0?}, {0xc000437ef8?, 0xc200000000000000?, 0x6?})
	reflect/value.go:380 +0xb9 fp=0xc000437e28 sp=0xc000437db0 pc=0x269b39
github.com/markus-wa/godispatch.callConsumerCode({0x5461a0?, 0xc000008840?, 0x5d3de0?}, {0xc000437ef8?, 0x1b70a6?, 0x1dd8ce?})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:125 +0x3f fp=0xc000437e78 sp=0xc000437e28 pc=0x459a7f
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc0000785a0, {0x62ee40, 0xc0001b4750})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:111 +0x1d4 fp=0xc000437f20 sp=0xc000437e78 pc=0x4599d4
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover(0xc0000785b8?, {0x62ee40?, 0xc0001b4750?})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:202 +0x4f fp=0xc000437f68 sp=0xc000437f20 pc=0x45a36f
github.com/markus-wa/godispatch.(*Dispatcher).dispatchQueue(0xc0000785a0, 0x0?)
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:177 +0xd0 fp=0xc000437fc0 sp=0xc000437f68 pc=0x45a290
github.com/markus-wa/godispatch.(*Dispatcher).AddQueues.func2()
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:162 +0x25 fp=0xc000437fe0 sp=0xc000437fc0 pc=0x45a125
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc000437fe8 sp=0xc000437fe0 pc=0x2085c1
created by github.com/markus-wa/godispatch.(*Dispatcher).AddQueues in goroutine 1
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:162 +0x18a

goroutine 1 [semacquire]:
runtime.gopark(0x2?, 0xc2429f0d00?, 0x20?, 0x3c?, 0x1a8b57?)
	runtime/proc.go:398 +0xce fp=0xc0004332d8 sp=0xc0004332b8 pc=0x1dd8ce
runtime.goparkunlock(...)
	runtime/proc.go:404
runtime.semacquire1(0xc0000785c0, 0x60?, 0x1, 0x0, 0x60?)
	runtime/sema.go:160 +0x229 fp=0xc000433340 sp=0xc0004332d8 pc=0x1ebd69
sync.runtime_Semacquire(0x45ac60?)
	runtime/sema.go:62 +0x25 fp=0xc000433378 sp=0xc000433340 pc=0x2044c5
sync.(*WaitGroup).Wait(0xc0000785a0?)
	sync/waitgroup.go:116 +0x48 fp=0xc0004333a0 sp=0xc000433378 pc=0x215b48
github.com/markus-wa/godispatch.(*Dispatcher).sendToken(0xc0000785a0, {0xc00006a0a0?, 0x150ab?, 0x201d00?}, {0x52cd60?, 0x6bca00?})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:282 +0x11b fp=0xc000433430 sp=0xc0004333a0 pc=0x45a97b
github.com/markus-wa/godispatch.(*Dispatcher).SyncQueues(...)
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:240
github.com/markus-wa/godispatch.(*Dispatcher).SyncAllQueues(...)
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:245
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).handleStringTables(0xc000061860, 0xc2429d8ac0)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/stringtables.go:532 +0x53 fp=0xc000433508 sp=0xc000433430 pc=0x4944b3
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).handleFullPacket(0xc242a20000?, 0xc2429d8a80)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/s2_commands.go:361 +0x25 fp=0xc000433530 sp=0xc000433508 pc=0x490fa5
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).parseFrameS2(0xc000061860)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/parsing.go:380 +0x331 fp=0xc000433610 sp=0xc000433530 pc=0x48c811
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).parseFrameS2-fm()
	<autogenerated>:1 +0x25 fp=0xc000433628 sp=0xc000433610 pc=0x49e0a5
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).ParseToEnd(0xc000061860)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/parsing.go:147 +0x146 fp=0xc000433780 sp=0xc000433628 pc=0x48b646
github.com/akiver/cs-demo-analyzer/pkg/api.analyzeDemo({0xc0000360fb, 0x39}, {0x40?, {0xc00000a148?, 0x1?}})
	github.com/akiver/cs-demo-analyzer/pkg/api/analyzer.go:208 +0xb89 fp=0xc000433e38 sp=0xc000433780 pc=0x4a0569
github.com/akiver/cs-demo-analyzer/pkg/api.AnalyzeAndExportDemo({0xc0000360fb?, 0x39?}, {0xc00002c248, 0x34}, {0x0, {0xc00000a148, 0x4}, {0xc00000a118, 0x4}, 0x0})
	github.com/akiver/cs-demo-analyzer/pkg/api/analyzer.go:252 +0x6c fp=0xc000433e70 sp=0xc000433e38 pc=0x4a0a0c
github.com/akiver/cs-demo-analyzer/pkg/cli.Run({0xc00011e010, 0x4, 0x7})
	github.com/akiver/cs-demo-analyzer/pkg/cli/cli.go:77 +0xfb fp=0xc000433f18 sp=0xc000433e70 pc=0x4e9c5b
main.main()
	github.com/akiver/cs-demo-analyzer/cmd/cli/cli.go:10 +0x45 fp=0xc000433f40 sp=0xc000433f18 pc=0x4e9e65
runtime.main()
	runtime/proc.go:267 +0x2b2 fp=0xc000433fe0 sp=0xc000433f40 pc=0x1dd4b2
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc000433fe8 sp=0xc000433fe0 pc=0x2085c1

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc000063fa8 sp=0xc000063f88 pc=0x1dd8ce
runtime.goparkunlock(...)
	runtime/proc.go:404
runtime.forcegchelper()
	runtime/proc.go:322 +0xb8 fp=0xc000063fe0 sp=0xc000063fa8 pc=0x1dd758
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc000063fe8 sp=0xc000063fe0 pc=0x2085c1
created by runtime.init.6 in goroutine 1
	runtime/proc.go:310 +0x1a

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc000065f78 sp=0xc000065f58 pc=0x1dd8ce
runtime.goparkunlock(...)
	runtime/proc.go:404
runtime.bgsweep(0x0?)
	runtime/mgcsweep.go:321 +0xdf fp=0xc000065fc8 sp=0xc000065f78 pc=0x1c819f
runtime.gcenable.func1()
	runtime/mgc.go:200 +0x25 fp=0xc000065fe0 sp=0xc000065fc8 pc=0x1bd2e5
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc000065fe8 sp=0xc000065fe0 pc=0x2085c1
created by runtime.gcenable in goroutine 1
	runtime/mgc.go:200 +0x66

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc000038070?, 0x6baef0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc000075f70 sp=0xc000075f50 pc=0x1dd8ce
runtime.goparkunlock(...)
	runtime/proc.go:404
runtime.(*scavengerState).park(0xaf40e0)
	runtime/mgcscavenge.go:425 +0x49 fp=0xc000075fa0 sp=0xc000075f70 pc=0x1c5a29
runtime.bgscavenge(0x0?)
	runtime/mgcscavenge.go:658 +0x59 fp=0xc000075fc8 sp=0xc000075fa0 pc=0x1c5fd9
runtime.gcenable.func2()
	runtime/mgc.go:201 +0x25 fp=0xc000075fe0 sp=0xc000075fc8 pc=0x1bd285
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc000075fe8 sp=0xc000075fe0 pc=0x2085c1
created by runtime.gcenable in goroutine 1
	runtime/mgc.go:201 +0xa5

goroutine 5 [finalizer wait]:
runtime.gopark(0x0?, 0x400000?, 0x70?, 0x7e?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc000067e20 sp=0xc000067e00 pc=0x1dd8ce
runtime.runfinq()
	runtime/mfinal.go:193 +0x107 fp=0xc000067fe0 sp=0xc000067e20 pc=0x1bc347
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc000067fe8 sp=0xc000067fe0 pc=0x2085c1
created by runtime.createfing in goroutine 1
	runtime/mfinal.go:163 +0x3d

goroutine 7 [GC worker (idle)]:
runtime.gopark(0xb48280?, 0x3?, 0x54?, 0x2e?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc000071f50 sp=0xc000071f30 pc=0x1dd8ce
runtime.gcBgMarkWorker()
	runtime/mgc.go:1295 +0xe5 fp=0xc000071fe0 sp=0xc000071f50 pc=0x1beee5
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc000071fe8 sp=0xc000071fe0 pc=0x2085c1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1219 +0x1c

goroutine 8 [GC worker (idle)]:
runtime.gopark(0xb48280?, 0x3?, 0xd4?, 0x8?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc000073f50 sp=0xc000073f30 pc=0x1dd8ce
runtime.gcBgMarkWorker()
	runtime/mgc.go:1295 +0xe5 fp=0xc000073fe0 sp=0xc000073f50 pc=0x1beee5
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc000073fe8 sp=0xc000073fe0 pc=0x2085c1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1219 +0x1c

goroutine 18 [GC worker (idle)]:
runtime.gopark(0xb48280?, 0x3?, 0x58?, 0x4e?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc00008ff50 sp=0xc00008ff30 pc=0x1dd8ce
runtime.gcBgMarkWorker()
	runtime/mgc.go:1295 +0xe5 fp=0xc00008ffe0 sp=0xc00008ff50 pc=0x1beee5
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc00008ffe8 sp=0xc00008ffe0 pc=0x2085c1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1219 +0x1c

goroutine 19 [GC worker (idle)]:
runtime.gopark(0xb48280?, 0x1?, 0xb4?, 0x9?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc000091f50 sp=0xc000091f30 pc=0x1dd8ce
runtime.gcBgMarkWorker()
	runtime/mgc.go:1295 +0xe5 fp=0xc000091fe0 sp=0xc000091f50 pc=0x1beee5
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc000091fe8 sp=0xc000091fe0 pc=0x2085c1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1219 +0x1c

goroutine 34 [GC worker (idle)]:
runtime.gopark(0x1bebcbb79a8?, 0x1?, 0x10?, 0xa1?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc000077f50 sp=0xc000077f30 pc=0x1dd8ce
runtime.gcBgMarkWorker()
	runtime/mgc.go:1295 +0xe5 fp=0xc000077fe0 sp=0xc000077f50 pc=0x1beee5
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc000077fe8 sp=0xc000077fe0 pc=0x2085c1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1219 +0x1c

goroutine 9 [GC worker (idle)]:
runtime.gopark(0xb48280?, 0x1?, 0xb4?, 0x9?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc00008bf50 sp=0xc00008bf30 pc=0x1dd8ce
runtime.gcBgMarkWorker()
	runtime/mgc.go:1295 +0xe5 fp=0xc00008bfe0 sp=0xc00008bf50 pc=0x1beee5
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc00008bfe8 sp=0xc00008bfe0 pc=0x2085c1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1219 +0x1c

goroutine 10 [GC worker (idle)]:
runtime.gopark(0xb48280?, 0x3?, 0xc0?, 0xbd?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc00008df50 sp=0xc00008df30 pc=0x1dd8ce
runtime.gcBgMarkWorker()
	runtime/mgc.go:1295 +0xe5 fp=0xc00008dfe0 sp=0xc00008df50 pc=0x1beee5
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc00008dfe8 sp=0xc00008dfe0 pc=0x2085c1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1219 +0x1c

goroutine 35 [GC worker (idle)]:
runtime.gopark(0xb48280?, 0x3?, 0x74?, 0x24?, 0x0?)
	runtime/proc.go:398 +0xce fp=0xc000451f50 sp=0xc000451f30 pc=0x1dd8ce
runtime.gcBgMarkWorker()
	runtime/mgc.go:1295 +0xe5 fp=0xc000451fe0 sp=0xc000451f50 pc=0x1beee5
runtime.goexit()
	runtime/asm_amd64.s:1650 +0x1 fp=0xc000451fe8 sp=0xc000451fe0 pc=0x2085c1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	runtime/mgc.go:1219 +0x1c

### Environment information

Version: 3.2.0
OS: win32 x64 10.0.19045
Electron: 28.1.1
Chrome: 120.0.6099.109
Last database migrations:
v1 - 2024-02-08T16:48:36.768Z

### Additional context

All demo sources give the same error

**Comment by artemmiz1** [comment]
Sorry, didn't read the last notes as that's an issue being worked on
