### ISSUE TITLE
Error Analyzing Demo

### ISSUE THREAD

**Issue by Asviix** [akiver/cs-demo-manager#774]
### Describe the bug

```
runtime error: invalid memory address or nil pointer dereference
stacktrace:
goroutine 6 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x5e
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.NewParserWithConfig.func1({0x59fbc0?, 0xc001f0a9c0})
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/parser.go:403 +0x2f
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover.func1()
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:197 +0x3b
panic({0x59fbc0?, 0xc001f0a9c0?})
	runtime/panic.go:914 +0x21f
github.com/markus-wa/godispatch.callConsumerCode.func1()
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:122 +0x54
panic({0x56d960?, 0xb04400?})
	runtime/panic.go:914 +0x21f
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs.(*parser).bindGameRules.func1.9({{0x0, 0x0, 0x0}, 0x0, 0x0, {0x0, 0x0, 0x0}, {0x6d0918, 0x0}, ...})
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/datatables.go:1394 +0x245
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/sendtables2.(*Entity).readFields(0xc0002b8af0, 0xc0002b7d10?, 0xc000ba1608)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/sendtables2/entity.go:450 +0x319
github.com/markus-wa/demoinfocs-golang/v4/pkg/demoinfocs/sendtables2.(*Parser).OnPacketEntities(0xc00007caf0, 0xc000a86000)
	github.com/markus-wa/demoinfocs-golang/v4@v4.0.0/pkg/demoinfocs/sendtables2/entity.go:558 +0x698
reflect.Value.call({0x54d760?, 0xc000008858?, 0xc0002b78c0?}, {0x65db00, 0x4}, {0xc000ba1ef8, 0x1, 0x0?})
	reflect/value.go:596 +0xce7
reflect.Value.Call({0x54d760?, 0xc000008858?, 0x58?}, {0xc000ba1ef8?, 0x820000c000061b01?, 0x3?})
	reflect/value.go:380 +0xb9
github.com/markus-wa/godispatch.callConsumerCode({0x54d760?, 0xc000008858?, 0xc000044000?}, {0xc000ba1ef8?, 0x1b72e6?, 0x0?})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:125 +0x3f
github.com/markus-wa/godispatch.(*Dispatcher).Dispatch(0xc000042600, {0x643d60, 0xc000a86000})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:111 +0x1d4
github.com/markus-wa/godispatch.(*Dispatcher).dispatchWithRecover(0xc000042618?, {0x643d60?, 0xc000a86000?})
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:202 +0x4f
github.com/markus-wa/godispatch.(*Dispatcher).dispatchQueue(0xc000042600, 0x0?)
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:177 +0xd0
created by github.com/markus-wa/godispatch.(*Dispatcher).AddQueues in goroutine 1
	github.com/markus-wa/godispatch@v1.4.1/dispatch.go:162 +0x18a
```

### Demo links

https://www.faceit.com/en/cs2/room/1-c4fc31cb-0750-430d-9590-ee6cf32c158d

### Steps to reproduce

1. Analyze this demo
2. Error Occurs

### Expected behavior

I would expect the demo to analyzed but fails

### How often does this bug happen?

Every time

### Environment information

Version: 3.3.1
OS: win32 x64 10.0.22631
Electron: 29.0.1
Chrome: 122.0.6261.57
Last database migrations:
v1 - 2024-02-23T16:59:23.274Z

**Comment by akiver** [comment]
fixed in https://github.com/markus-wa/demoinfocs-golang/pull/516
