### ISSUE TITLE
Error analizing Inferno, twice, consecutive games.

### ISSUE THREAD

**Issue by CaliburNS** [akiver/cs-demo-manager#802]
### Describe the bug

Unknown error analyzing demo on CS2 with CS Demo Manager.

### Steps to reproduce

Analize a demo.

### Expected behavior

End analizing and give success message.

### How often does this bug happen?

None

### Log file

Grenade nil in decoy start event
Grenade nil in decoy start event
Grenade nil in decoy start event
Grenade nil in decoy start event
Grenade nil in decoy start event
Grenade nil in decoy start event
Match not found
Error: Match not found
    at Ewe (C:\Users\MrFinch\AppData\Local\Programs\cs-demo-manager\resources\src\node\database\matches\fetch-match-table.ts:30:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at nIe (C:\Users\MrFinch\AppData\Local\Programs\cs-demo-manager\resources\src\node\database\matches\process-match-insertion.ts:36:17)
    at Qj.insertMatch (C:\Users\MrFinch\AppData\Local\Programs\cs-demo-manager\resources\src\server\analyses-listener.ts:163:21)
    at Qj.processAnalysis (C:\Users\MrFinch\AppData\Local\Programs\cs-demo-manager\resources\src\server\analyses-listener.ts:142:7)
    at e (C:\Users\MrFinch\AppData\Local\Programs\cs-demo-manager\resources\src\server\analyses-listener.ts:97:11)
    at Qj.loopUntilAnalysesDone (C:\Users\MrFinch\AppData\Local\Programs\cs-demo-manager\resources\src\server\analyses-listener.ts:105:5)
    at Qj.addDemosToAnalyses (C:\Users\MrFinch\AppData\Local\Programs\cs-demo-manager\resources\src\server\analyses-listener.ts:61:5)
    at USe (C:\Users\MrFinch\AppData\Local\Programs\cs-demo-manager\resources\src\server\handlers\renderer-process\demo\add-demos-to-analyses-handler.ts:5:3)
    at t.onRendererProcessSocketMessage (C:\Users\MrFinch\AppData\Local\Programs\cs-demo-manager\resources\src\server\server.ts:177:26)

### Environment information

Win 10
Latest CS2, Latest CSDM, 
PostgreSQL 16 on Debian 12.

### Additional context

Two consecuttive Inferno demos.

**Comment by akiver** [comment]
Could you upload the demo please?

**Comment by giou** [comment]
I have the same issue with multiple demos, where do you want me to upload them? @akiver

**Comment by akiver** [comment]
Could you upload the second demo (`match730_003685800597518286980_0157631789_195.dem`)?
You can use Mega, Dropbox...

**Comment by giou** [comment]
> Could you upload the second demo (`match730_003685800597518286980_0157631789_195.dem`)? You can use Mega, Dropbox...

https://mega.nz/file/cwsSWA7J#Ee1Ql4Ws78y4nfztjhBnUwnra0b3evM6xQfIwEnWq5Y
