### ISSUE TITLE
Runtime error: TypeError: useVideosState.videos is not iterable

### ISSUE THREAD

**Issue by tintinmaster** [akiver/cs-demo-manager#899]
### Describe the bug

Crash on startup

### Steps to reproduce

1. Start the application

### Expected behavior

I would expect the application to start normally, but It crashes instantly

### How often does this bug happen?

Every time

### Log file

https://gist.github.com/tintinmaster/a6a3df5bae8a272e50cb82f63f10900d

### Environment information

Version: 3.7.1
OS: linux x64 6.5.0-45-generic
Electron: 31.2.0
Chrome: 126.0.6478.127

### Additional context

```
TypeError: useVideosState.videos is not iterable
    at useVideos (file:///opt/CS%20Demo%20Manager/resources/app.asar/assets/index-D2pjG_5O.js:125:2896)
    at PendingVideosBadge (file:///opt/CS%20Demo%20Manager/resources/app.asar/assets/index-D2pjG_5O.js:125:3047)
    at Nh (file:///opt/CS%20Demo%20Manager/resources/app.asar/assets/index-D2pjG_5O.js:38:18176)
    at Vk (file:///opt/CS%20Demo%20Manager/resources/app.asar/assets/index-D2pjG_5O.js:40:45960)
    at Uk (file:///opt/CS%20Demo%20Manager/resources/app.asar/assets/index-D2pjG_5O.js:40:41468)
    at Tk (file:///opt/CS%20Demo%20Manager/resources/app.asar/assets/index-D2pjG_5O.js:40:41391)
    at Ik (file:///opt/CS%20Demo%20Manager/resources/app.asar/assets/index-D2pjG_5O.js:40:41234)
    at Nk (file:///opt/CS%20Demo%20Manager/resources/app.asar/assets/index-D2pjG_5O.js:40:37419)
    at Gk (file:///opt/CS%20Demo%20Manager/resources/app.asar/assets/index-D2pjG_5O.js:40:36331)
    at J2 (file:///opt/CS%20Demo%20Manager/resources/app.asar/assets/index-D2pjG_5O.js:25:1649)
```

**Comment by akiver** [comment]
I can't reproduce the crash, does it happen when you start the app or while using it?
What's your Linux distro?
