### ISSUE TITLE
CS Demo Manager Unable to Recognize HLAE Executable “invalid hlae executable”

### ISSUE THREAD

**Issue by alazeria** [akiver/cs-demo-manager#959]
### Describe the bug

I am encountering an issue while using CS Demo Manager, where I am aiming to optimize my workflow by generating videos automatically instead of manual recordings. To achieve this, I installed HLAE (specifically version 2.175, downloaded from GitHub). However, when attempting to specify the location of HLAE.exe in the settings of CS Demo Manager, I receive an error message: "invalid hlae executable".

To troubleshoot this issue, I have taken the following steps:

Reinstalled HLAE: I re-downloaded the HLAE 2.175 release and installed it according to the instructions, but the problem persists.
Used CS Demo Manager's Built-in HLAE Installation Feature: I tried installing HLAE through the built-in installation feature of CS Demo Manager, but only received an error message stating: "An error occurred while installing HLAE".
Possible reasons for this issue could include:

I may have installed an incompatible version of HLAE with CS Demo Manager.
I may have installed CS Demo Manager at an inappropriate update point, possibly requiring a wait for updates related to CS:GO or associated software.
To assist in diagnosing the problem more accurately, I would appreciate the following information, if possible:

The current version of CS Demo Manager.(V3.9.1)
The current version of CS:GO(30 October 2024 – 22:31:55 UTC), and whether any relevant updates or patches have been installed.
Whether other users have reported similar issues or if there are known compatibility problems.
I am eager to resolve this issue promptly so that I can utilize the functionality of HLAE and CS Demo Manager for automatic video generation. If you require any additional information or log files, please let me know.

### Steps to reproduce

Launch the Application: Start CS Demo Manager.
Navigate to Settings and Select Video:
Within the application, go to the settings menu.
Locate the section related to video settings.
Choose the option to use a custom location for HLAE.
When specifying the path to the HLAE executable, an error message appears: "invalid hlae executable".
Attempt to Use Built-in Installation Feature:
Return to the settings menu or the relevant section where you can manage HLAE.
Click on the button to install HLAE using the built-in feature provided by CS Demo Manager.
An error message is displayed: "An error occurred while installing HLAE".

### Expected behavior

I expect CS Demo Manager to correctly recognize and utilize the HLAE executable file. I have attempted to manually inject HLAE, and it works as intended. As a complete novice in video editing, I have been following a beginner's guide to CS video editing that I found online. The first step in this guide is to use CS Demo Manager. However, I am frustrated and stuck at this point.

My goal is to be able to use CS Demo Manager to generate videos automatically with the help of HLAE, without encountering any errors or compatibility issues. I believe that the software should seamlessly integrate with HLAE, allowing users like myself, who are new to the process, to easily create and edit videos.

### How often does this bug happen?

Every time

### Log file

Sat, 02 Nov 2024 17:25:58 GMT | ERROR | server | 1
Sat, 02 Nov 2024 17:26:02 GMT | LOG | server | WS:: renderer process socket disconnected 1001 { type: 'Buffer', data: [] }
Sat, 02 Nov 2024 17:26:06 GMT | LOG | server | WS:: renderer process socket connected
Sat, 02 Nov 2024 17:26:06 GMT | LOG | server | WS:: message with name connect-database and uuid 592626e9-d784-4007-b4d2-06c1fb5d93ec received from renderer process
Sat, 02 Nov 2024 17:26:06 GMT | LOG | renderer | WS:: connecting to server
Sat, 02 Nov 2024 17:26:06 GMT | LOG | renderer | WS:: connected
Sat, 02 Nov 2024 17:26:06 GMT | LOG | server | WS:: message with name init-application and uuid 3b4359d4-8b08-4b20-a29d-53a7a273d343 received from renderer process
Sat, 02 Nov 2024 17:26:06 GMT | LOG | server | WS:: message with name fetch-matches-table and uuid 12a4cc9b-5783-4f13-8be5-a1caf4de45a8 received from renderer process
Sat, 02 Nov 2024 17:26:12 GMT | LOG | server | WS:: message with name get-database-size and uuid c2b7b719-2d3e-4de5-8b74-c8f2e85ecb0c received from renderer process
Sat, 02 Nov 2024 17:26:18 GMT | LOG | server | WS:: message with name enable-hlae-custom-location and uuid 21a7c919-707d-4706-8b59-d81fd32223cd received from renderer process
Sat, 02 Nov 2024 17:26:21 GMT | LOG | server | WS:: message with name enable-hlae-custom-location and uuid 1bd913bf-694b-40a7-8d1e-6b819a85b099 received from renderer process
Sat, 02 Nov 2024 17:26:21 GMT | ERROR | server | Error while getting HLAE version from executable
Sat, 02 Nov 2024 17:26:21 GMT | ERROR | server | Error: Command failed: wmic datafile where 'name="C:\\Program Files (x86)\\HLAE\\HLAE.exe"' get version
'wmic'      ڲ    ⲿ   Ҳ   ǿ    еĳ   
         ļ   

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:305:5)

==============================================================================
Sat, 02 Nov 2024 16:36:34 GMT | ERROR | server | Network error while calling https://api.steampowered.com/ISteamUser/GetPlayerSummaries/v2/?key=A88961AFA9FBA9B584706B2C5E97DB4A&steamids=76561198953082613,76561199201916790,76561199199147700,76561198413153905,76561199701450856,76561199774994580,76561199761701657,76561199798498088,76561199795427636,76561199797681222
Sat, 02 Nov 2024 16:36:34 GMT | ERROR | server | TypeError: fetch failed
    at node:internal/deps/undici/undici:13178:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at globalThis.fetch (C:\Users\alazeria\AppData\Local\Programs\cs-demo-manager\resources\src\server\server.ts:342:12)
    at C:\Users\alazeria\AppData\Local\Programs\cs-demo-manager\resources\src\node\steam-web-api\get-users-summary.ts:46:26
    at async Promise.all (index 0)
    at Vm (C:\Users\alazeria\AppData\Local\Programs\cs-demo-manager\resources\src\node\steam-web-api\get-users-summary.ts:68:7)
    at du (C:\Users\alazeria\AppData\Local\Programs\cs-demo-manager\resources\src\node\database\steam-accounts\build-steam-accounts-from-steam-ids.ts:10:17)
    at gfe (C:\Users\alazeria\AppData\Local\Programs\cs-demo-manager\resources\src\node\database\matches\process-match-insertion.ts:21:27)
    at v$.insertMatch (C:\Users\alazeria\AppData\Local\Programs\cs-demo-manager\resources\src\server\analyses-listener.ts:144:21)
    at v$.processAnalysis (C:\Users\alazeria\AppData\Local\Programs\cs-demo-manager\resources\src\server\analyses-listener.ts:123:7)
	CAUSE: Error: unable to verify the first certificate
Sat, 02 Nov 2024 16:36:34 GMT | WARN | server | Network error
Sat, 02 Nov 2024 16:36:34 GMT | WARN | server | Communication error with the Steam API, it doesn't prevent match insertion.
Sat, 02 Nov 2024 16:36:34 GMT | LOG | renderer | WS:: message with name "analysis-status-changed" received from server
Sat, 02 Nov 2024 16:36:34 GMT | LOG | renderer | WS:: message with name "match-inserted" received from server
Sat, 02 Nov 2024 16:36:37 GMT | LOG | server | WS:: message with name fetch-match-by-checksum and uuid 0d0fd8bb-eb4c-4373-8012-ff12fe33a110 received from renderer process
Sat, 02 Nov 2024 16:36:47 GMT | LOG | server | WS:: message with name initialize-video and uuid d56c45f7-e465-4cff-bdeb-7efc15e38112 received from renderer process
Sat, 02 Nov 2024 16:37:12 GMT | LOG | server | WS:: message with name install-hlae and uuid c18e8193-4e04-47b0-8f2f-c853b74f7241 received from renderer process
Sat, 02 Nov 2024 16:37:12 GMT | ERROR | server | Network error while calling https://api.github.com/repos/advancedfx/advancedfx/releases
Sat, 02 Nov 2024 16:37:12 GMT | ERROR | server | TypeError: fetch failed
    at node:internal/deps/undici/undici:13178:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at globalThis.fetch (C:\Users\alazeria\AppData\Local\Programs\cs-demo-manager\resources\src\server\server.ts:342:12)
    at xD (C:\Users\alazeria\AppData\Local\Programs\cs-demo-manager\resources\src\node\video\hlae\fetch-last-hlae-release.ts:2:20)
    at uk (C:\Users\alazeria\AppData\Local\Programs\cs-demo-manager\resources\src\node\video\hlae\download-hlae.ts:9:19)
    at cVe (C:\Users\alazeria\AppData\Local\Programs\cs-demo-manager\resources\src\server\handlers\renderer-process\video\install-hlae-handler.ts:8:21)
    at t.onRendererProcessSocketMessage (C:\Users\alazeria\AppData\Local\Programs\cs-demo-manager\resources\src\server\server.ts:175:26)
	CAUSE: Error: unable to verify the first certificate
Sat, 02 Nov 2024 16:37:12 GMT | ERROR | server | Error: Network error
    at globalThis.fetch (C:\Users\alazeria\AppData\Local\Programs\cs-demo-manager\resources\src\server\server.ts:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at xD (C:\Users\alazeria\AppData\Local\Programs\cs-demo-manager\resources\src\node\video\hlae\fetch-last-hlae-release.ts:2:20)
    at uk (C:\Users\alazeria\AppData\Local\Programs\cs-demo-manager\resources\src\node\video\hlae\download-hlae.ts:9:19)
    at cVe (C:\Users\alazeria\AppData\Local\Programs\cs-demo-manager\resources\src\server\handlers\renderer-process\video\install-hlae-handler.ts:8:21)
    at t.onRendererProcessSocketMessage (C:\Users\alazeria\AppData\Local\Programs\cs-demo-manager\resources\src\server\server.ts:175:26)
Sat, 02 Nov 2024 16:37:12 GMT | ERROR | server | Error while installing HLAE
Sat, 02 Nov 2024 16:37:12 GMT | ERROR | server | Error: An error occurred while contacting GitHub
    at uk (C:\Users\alazeria\AppData\Local\Programs\cs-demo-manager\resources\src\node\video\hlae\download-hlae.ts:16:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at cVe (C:\Users\alazeria\AppData\Local\Programs\cs-demo-manager\resources\src\server\handlers\renderer-process\video\install-hlae-handler.ts:8:21)
    at t.onRendererProcessSocketMessage (C:\Users\alazeria\AppData\Local\Programs\cs-demo-manager\resources\src\server\server.ts:175:26)
Sat, 02 Nov 2024 16:37:12 GMT | ERROR | server | 1
Sat, 02 Nov 2024 16:37:12 GMT | ERROR | server | WS:: error handling message with install-hlae from renderer process
Sat, 02 Nov 2024 16:37:14 GMT | LOG | server | WS:: message with name install-hlae and uuid 4dcbba9a-d474-424e-ac5f-3879a7119b5f received from renderer process
Sat, 02 Nov 2024 16:37:14 GMT | ERROR | server | TypeError: fetch failed
    at node:internal/deps/undici/undici:13178:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at globalThis.fetch (C:\Users\alazeria\AppData\Local\Programs\cs-demo-manager\resources\src\server\server.ts:342:12)
    at xD (C:\Users\alazeria\AppData\Local\Programs\cs-demo-manager\resources\src\node\video\hlae\fetch-last-hlae-release.ts:2:20)
    at uk (C:\Users\alazeria\AppData\Local\Programs\cs-demo-manager\resources\src\node\video\hlae\download-hlae.ts:9:19)
    at cVe (C:\Users\alazeria\AppData\Local\Programs\cs-demo-manager\resources\src\server\handlers\renderer-process\video\install-hlae-handler.ts:8:21)
    at t.onRendererProcessSocketMessage (C:\Users\alazeria\AppData\Local\Programs\cs-demo-manager\resources\src\server\server.ts:175:26)
	CAUSE: Error: unable to verify the first certificate
Sat, 02 Nov 2024 16:37:14 GMT | ERROR | server | Network error while calling https://api.github.com/repos/advancedfx/advancedfx/releases
Sat, 02 Nov 2024 16:37:14 GMT | ERROR | server | Error: Network error
    at globalThis.fetch (C:\Users\alazeria\AppData\Local\Programs\cs-demo-manager\resources\src\server\server.ts:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at xD (C:\Users\alazeria\AppData\Local\Programs\cs-demo-manager\resources\src\node\video\hlae\fetch-last-hlae-release.ts:2:20)
    at uk (C:\Users\alazeria\AppData\Local\Programs\cs-demo-manager\resources\src\node\video\hlae\download-hlae.ts:9:19)
    at cVe (C:\Users\alazeria\AppData\Local\Programs\cs-demo-manager\resources\src\server\handlers\renderer-process\video\install-hlae-handler.ts:8:21)
    at t.onRendererProcessSocketMessage (C:\Users\alazeria\AppData\Local\Programs\cs-demo-manager\resources\src\server\server.ts:175:26)
Sat, 02 Nov 2024 16:37:14 GMT | ERROR | server | Error while installing HLAE
Sat, 02 Nov 2024 16:37:14 GMT | ERROR | server | Error: An error occurred while contacting GitHub
    at uk (C:\Users\alazeria\AppData\Local\Programs\cs-demo-manager\resources\src\node\video\hlae\download-hlae.ts:16:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at cVe (C:\Users\alazeria\AppData\Local\Programs\cs-demo-manager\resources\src\server\handlers\renderer-process\video\install-hlae-handler.ts:8:21)
    at t.onRendererProcessSocketMessage (C:\Users\alazeria\AppData\Local\Programs\cs-demo-manager\resources\src\server\server.ts:175:26)
Sat, 02 Nov 2024 16:37:14 GMT | ERROR | server | 1
Sat, 02 Nov 2024 16:37:14 GMT | ERROR | server | WS:: error handling message with install-hlae from renderer process
Sat, 02 Nov 2024 16:38:11 GMT | LOG | server | WS:: message with name fetch-last-migrations and uuid 26a74eae-a68c-4f7b-9ff5-d8da0fa799a8 received from renderer process
Sat, 02 Nov 2024 16:38:13 GMT | LOG | server | WS:: message with name get-database-size and uuid 65794761-30bd-4b32-87bb-cb272676912d received from renderer process
Sat, 02 Nov 2024 16:38:24 GMT | LOG | server | WS:: message with name has-pending-analyses and uuid 44f48f98-888b-43f3-a314-ae6fab07549b received from main process
Sat, 02 Nov 2024 16:38:24 GMT | WARN | main | WS:: disconnected

### Environment information

Version: 3.9.1
OS: win32 x64 10.0.26100
Electron: 31.6.0
Chrome: 126.0.6478.234
Last database migrations:
v5 - 2024-11-03T00:33:23.360Z

### Additional context

Please be advised that this issue has been translated using an AI large model. As a result, some of the wording and tone may appear more aggressive than intended. I apologize for any inconvenience this may cause and appreciate your understanding. English is not my primary language, and I have done my best to convey my issue clearly.

Thank you for your attention to this matter.

**Comment by alazeria** [comment]
I believe the issue has been mostly resolved. After thorough troubleshooting, I discovered that Windows Security Center flagged the file downloaded for the HLAE functionality as containing a virus: Trojan:AndroidOS/ZkarletFlash. Although I was able to complete my intended task using the built-in installation feature, specifying the HLAE manually still seems to be unavailable.
﻿
To clarify, the built-in installation process worked as expected and allowed me to achieve my goals. However, there seems to be an issue when attempting to manually specify the HLAE path or file. This might be related to the security warning from Windows Security Center, which could have potentially blocked or quarantined the file.
﻿
I understand that this may be a false positive and that the file is safe to use. 
﻿
Thank you for your attention to this matter.
